<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="USHYDSHMURAL5" name="com.DEvents.tests.TestAPI_GetParticipants" tests="6" failures="1" timestamp="2019-11-11T22:44:51 IST" time="5.672" errors="0">
  <testcase name="checkStatusCode" time="0.001" classname="com.DEvents.tests.TestAPI_GetParticipants"/>
  <testcase name="checkResponseBody" time="4.509" classname="com.DEvents.tests.TestAPI_GetParticipants">
    <failure type="java.lang.AssertionError" message="Found mismatch between Json output and Database results did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Found mismatch between Json output and Database results did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.DEvents.tests.TestAPI_GetParticipants.checkResponseBody(TestAPI_GetParticipants.java:117)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkContentEncoding" time="0.008" classname="com.DEvents.tests.TestAPI_GetParticipants"/>
  <testcase name="checkResponseTime" time="0.003" classname="com.DEvents.tests.TestAPI_GetParticipants"/>
  <testcase name="validateJSONSchema" time="1.150" classname="com.DEvents.tests.TestAPI_GetParticipants"/>
  <testcase name="checkContentType" time="0.001" classname="com.DEvents.tests.TestAPI_GetParticipants"/>
</testsuite> <!-- com.DEvents.tests.TestAPI_GetParticipants -->
